merge_queue:
  max_parallel_checks: 1
queue_rules:
  - name: default
    batch_size: 2
    batch_max_wait_time: 5 min
    queue_conditions: true
    merge_conditions:
      - check-success = vm4-closed-carry-gate
      - schedule = 03:25-03:40
    merge_method: merge-batch
